[[main]]
none = "none"

[[main]]
name = "About Me"
pageRef = "about-me"
identifier = "C5QZfcjI9H"
weight = 9999

[[main]]
name = "Experience"
pageRef = "experience"
identifier = "vbJbjkuuNc"
weight = 9999

[[main]]
name = "Projects"
pre = "github"
pageRef = "projects"
identifier = "Da2wSk089V"
weight = 9999

[[main]]
name = "Photography"
pre = "image"
pageRef = "photography"
identifier = "aIxl2kJjSC"
weight = 9999

[[footer]]
none = "none"
